CREATE DATABASE IF NOT EXISTS zongce DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'zongce'@'localhost' IDENTIFIED BY 'zongce123!';
GRANT ALL PRIVILEGES ON zongce.* TO 'zongce'@'localhost';
FLUSH PRIVILEGES;
